python main.py \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--pretrained models/gcnclassifier_v2_ones3_t0v1t2_lr1e-6_e80.pth \
--seed 3247671 \
--monitor_metric 'BLEU_1' \
--rm_num_slots 9 \
--num_workers 2 \
--num_layers 6 \
--flip ''
